module.exports = Object.freeze({
  VCARD_INCLUDED_FIELDS: [
    "X-GENDER",
    "N",
    "TITLE",
    "ORG",
    "ADR",
    "TEL",
    "EMAIL",
    "X-SOCIALPROFILE",
    "BDAY",
    "PHOTO",
    "URL",
    "NICKNAME,",
    "IMPP"
  ],
  VCARD_HEADLINES_MAPPING: [
    { Geschlecht: "X-GENDER" },
    { Vorname: "N:1" },
    { Mittelname: "N:2" },
    { Nachname: "N:3" },
    { Titel: "TITLE" },
    { Accountname: "ORG" },
    { "Strasse (Postanschrift)": "ADR:3" },
    { "Stadt (Postanschrift)": "ADR:4" },
    { "Bundesland (Postanschrift)": "ADR:5" },
    { "PLZ (Postanschrift)": "ADR:6" },
    { "Land (Postanschrift)": "ADR:7" },
    { Telefon: "TEL;TYPE=work,voice" },
    { Fax: "TEL;TYPE=work,fax" },
    { Mobiltelefon: "TEL;TYPE=cell,voice" },
    { "E-Mail": "EMAIL;TYPE=work" },
    { Accountinhaber: "" },
    { "LinkedIn ID": "X-SOCIALPROFILE;TYPE=linkedin" },
    { "Xing ID": "X-SOCIALPROFILE;TYPE=xing" },
    { "Twitter ID": "X-SOCIALPROFILE;TYPE=twitter" },
    { "Facebook ID": "X-SOCIALPROFILE;TYPE=facebook" },
    { "AboutMe ID": "X-SOCIALPROFILE;TYPE=aboutme" },
    { "Google ID": "X-SOCIALPROFILE;TYPE=google" },
    { Abteilung: "ORG:2" },
    { Geburtsdatum: "BDAY;ALTID=1" },
    { "Telefon privat": "TEL;TYPE=home,voice" },
    { "Postanschrift Zeile 1": "ADR:1" },
    { "Postanschrift Zeile 2": "ADR:1" },
    { Photo: "PHOTO;VALUE=uri" },
    { Website: "URL" },
    { Nickname: "NICKNAME" },
    { "Skype ID": "IMPP;X-SERVICE-TYPE=Skype:skype" }
  ],
  VCARD_HEADLINES_MAPPING_2: [
    { "X-GENDER": "Geschlecht" },
    { "N:2": "Vorname" },
    { "N:3": "Mittelname" },
    { "N:1": "Nachname" },
    { TITLE: "Titel" },
    { ORG: "Accountname" },
    { "ADR:3": "Strasse (Postanschrift)" },
    { "ADR:4": "Stadt (Postanschrift)" },
    { "ADR:5": "Bundesland (Postanschrift)" },
    { "ADR:6": "PLZ (Postanschrift)" },
    { "ADR:7": "Land (Postanschrift)" },
    { "TEL;TYPE=work,voice": "Telefon" },
    { "TEL;TYPE=work,fax": "Fax" },
    { "TEL;TYPE=cell,voice": "Mobiltelefon" },
    { "EMAIL;TYPE=work": "E-Mail" },
    { "": "Accountinhaber" },
    { "X-SOCIALPROFILE;TYPE=linkedin": "LinkedIn ID" },
    { "X-SOCIALPROFILE;TYPE=xing": "Xing ID" },
    { "X-SOCIALPROFILE;TYPE=twitter": "Twitter ID" },
    { "X-SOCIALPROFILE;TYPE=facebook": "Facebook ID" },
    { "X-SOCIALPROFILE;TYPE=aboutme": "AboutMe ID" },
    { "X-SOCIALPROFILE;TYPE=google": "Google ID" },
    { "ORG:2": "Abteilung" },
    { "BDAY;ALTID=1": "Geburtsdatum" },
    { "TEL;TYPE=home,voice": "Telefon privat" },
    { "ADR:1": "Postanschrift Zeile 1" },
    { "ADR:2": "Postanschrift Zeile 2" },
    { "PHOTO;VALUE=uri": "Photo" },
    { URL: "Website" },
    { NICKNAME: "Nickname" },
    { "IMPP;X-SERVICE-TYPE=Skype": "Skype ID" }
  ],
  PREFIX: "BEGIN:VCARD",
  POSTFIX: "END:VCARD"
});
